"""Initial migration

Revision ID: 182144a29881
Revises: 83bf19502339
Create Date: 2025-06-17 13:22:40.238674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182144a29881'
down_revision = '83bf19502339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
